# -*- coding: utf-8 -*-
"""superstore data analysis project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12PX4yHrSnT_GLIqHhipWHbUU-dvEQs4k
"""



from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

import pandas as pd
import numpy as np

df = pd.read_csv('train.csv.zip')
df.head()
df.tail()

df.info()
df.isnull().sum()

df.drop_duplicates(inplace=True)

#Top 5 customers
customer_sales = df.groupby('Customer Name')['Sales'].sum()
top_customers = customer_sales.sort_values(ascending=False).head(5)
display(top_customers)

#total sale
df['Sales'].sum()

#Top 5 products
product_sales = df.groupby('Product Name')['Sales'].sum()
top_products = product_sales.sort_values(ascending=True).head(5)
display(top_products)

#sales by region
region_sales = df.groupby('Region')['Sales'].sum()
region_sales = region_sales.sort_values(ascending=True).head(5)
display(region_sales)

#monthly trend
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d/%m/%Y')
df['Order Month'] = df['Order Date'].dt.to_period('M')
monthly_sales = df.groupby('Order Month')['Sales'].sum().sort_values(ascending=False)
display(monthly_sales)

"""Once your file is uploaded, you can load it into a pandas DataFrame by replacing `your_file_name.csv` with the actual name of your uploaded file."""